# Generated by Django 3.2 on 2021-08-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210825_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginfo',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.bookinginfo'),
        ),
    ]
